INSERT INTO "article" ("TITLE", "CONTENT", "AUTHOR", "CREATED_AT", "UPDATED_AT")
VALUES ('제목 1', '내용 1', 'user1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO "article" ("TITLE", "CONTENT", "AUTHOR", "CREATED_AT", "UPDATED_AT")
VALUES ('제목 2', '내용 2', 'user2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO "article" ("TITLE", "CONTENT", "AUTHOR", "CREATED_AT", "UPDATED_AT")
VALUES ('제목 3', '내용 3', 'user3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
